#数据源
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.18.51:3306/waimai?Unicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  jpa:
    show-sql: true

